const Strings={
   onBoardingTitle:'Everything on one place',
   onBoardingText:'Discover services you need.',
   onBoardingTitle1:'Quick Booking',
   onBoardingText1:'Track service availability in real time and book online.',
   logIn:'Log in',
   signUp:'Sign up',
   guest:'Guest',
   windsor:'Windsor',
   quickBooking:'QuickBooking',
   traclService:'Track service availability in real time and book online.',
   account:'Account',
   email:'Email',
   gender:'Gender',
   password:'Password',
   phoneNumber:'Phone Number',
   or:'or',
   alreadySigned:'Already Signed Up? ',
   accountPlaceHolder:'Enter your account here',
   emailPlaceHolder:'Enter your email here',
   passwordPlaceHolder:'Enter your password here',
   phonePlaceHolder:'Enter your phone #',
   search:'Search',
   countryOrRegion:'Country or region',
   confirmYourNumber:'Confirm your number',
   enterSixDigitCodeText:'Enter 6 digital number code we sent to',
   alreadyHaveCode:'Already have an code?',
   editNumber:'Edit Number',
   wrongCode:'Wrong code',
   enterCorrectCode:'Please enter the correct code',
   resendCode:'Resend code',
   forgotPassword:'Forgot password?',
   notAccount:'Don’t have an Account? ',
   resetPassword:'Reset password',
   resetPasswordText:'Enter email associated with your account and we’ll send instructions to reset your password.',
   checkeEmail:'Check your email',
   passwordInstruction:'We have sent a password recover instruction to your email.',
   openEmail:'Open email app',
   another:' another ',
   checkEmailSpam:'Did not receive the email? Check your spam filter or try',
   address:'address',
   createNewPassword:'Create new password',
   createNewPasswordText:'Your new password must be different from previous used password',
   save:'Save',
   emailAddress:'email address',
   repeatPassword:'Repeat Password',
   repeatePasswodPlaceHolder:'Enter your password again',
   phoneNumber:'Phone Number',
   cancel:'Cancel',
   discover:'Discover',
   whatsTrending:"What's trending",
   forYou:'For You',
   done:'Done',
   name:'Name',
   namePlaceHolder:'Enter your name here',
   next:'Next',
   apply:"Apply",
   notNow:'Not now',
   from:'from',
   viewMore:'view more',
   topMaster:'Top master at',
   services:'Services',
   seeAll:'see all',
   portfolio:'Portfolio',
   workingHours:'Working hours',
   dayOff:'Day off',
   beard:'Beard',
   hair:'Hair',
   womens:'Womens',
   mens:'Mens',
   shareExperience:'Share your experience',
   rateReview:'Rate & Review',
   post:'Post',
   booking:"Booking",
   confirmBooking:"Confirm booking",
   resend:'Resend',
   bookings:'Bookings',
   memories:'Memories',
   whatsNew:"What’s new",
   favorites:'Favorites',
   RewardsCredits:'Rewards credits',
   promoCodes:'promo codes',
   payment:'Payment',
   helpCenter:'Help center',
   termsPrivacyPolicy:'Terms and Privacy Policy',
   TermsAndPolicy:'Terms and \n Privacy Policy',
   edit:'Edit',
   PrivacyPolicy:'Privacy Policy',
   notifications:'Notifications',
   notificationSound:'Notification sound',
   reminders:'Reminders',
   calendar:'Calender',
   location:"Location",
   notificationSettings:'Notification',
   choosePhoto:'Choose photo',
   styleBot:'Style Bot',
   dexter:'Dexter',
   thora:'Thora',
   connectAccounts:'Connect accounts',
   remove:'Remove',
   facebook:'Facebook',
   google:'Google',
   takePhoto:'Take a photo',
   chooseFromLibrary:'Choose From Gallery',
   bookDetails:'Book details',
   reschedule:'Reschedule',
   thisMonth:'This month',
   allTime:"All time",
   book:'Book',
   PromoCodes:'Promo codes',
   nearYou:'Near you',
   rewardCredits:'Reward Credits',
   send:'Send',
   PaymentMethods:"Payment methods",
   transactionHistory:'Transactions history',
   cardHoldersName:"CardHolder's name",
   cardHolderPlaceholder:'Enter cardholder name',
   cardNumber:'Card Number',
   cardNumberPlaceholder:'Enter card number',
   expiryDate:'Expiry Date',
   expiryDatePlaceholder:'06/27',
   cvv:"CVV",
   cvvPlaceholder:'091',
   addCard:"Add card",
   AddDebitCredit:'Add debit/credit card',
   pay:"Pay",
   PayTipforMaster:'Pay a tip for the master',
   yes:"Yes",
   no:"No",
   addPhotoAfter:'Add photo after',
   before:"Before",
   after:"After",
   service:"Service",
   type:"Type",
   duration:"Duration",
   price:"Price",
   forMe:'For me',
   chooseTypeText:"Choose type",
   forSomeOneElse:"For someone else",
   TermOfUsers:'Term of users',
   chooseMaster: "Hey, time to choose a specialist you need and a service you want.",
   chooseType: 'Hey, time to choose a specialist you need and a service you want.',
   selectDate: 'Choose the date for your visit.',
   selectTime: "Choose time for your visit.",
   takePhotoBefore:"Take a before and after photo\n to compare the result.",
   takePhotoText: "After the treatment, take a photo after that to compare the result.",
   HelloJake: "Hello Jake!  \n \nWe hoping you service with Tony & Guys. We would appriciate your rating.  It will take less then a minute.",
   ThankYouJake: "Thank you Jake! \n\nYour feedback is very important for us. If you have suggestions or ideas how to improve Stylist app fell free to leave a comment below.",
   serviceID: [],
   min : null,
   max: null,
   searchArea:"Search for area, street name ...",


   // errors strings
   PLeaseEnterValidData : "PLease Enter valid Data",
   uploadiamge:"Please upload at least 1 iamge",
   enterReviewDetails: "Please enter review details",
   rate: "Please rate",
   InvalidEmailPassword : "Invalid Email or Password",
   TryAgain : "Something Went Wrong. Try Again",
   ChooseMaster : "Please Choose Master",
   validEmail:'Enter valid email address',
   enterEmail : 'Please Enter Email Address',
   enterName:'Please Enter Name',
   enterphone:'phone field must not be empty',
   minimumDigits:'Minimum 10 digits required',
   MaximumDigits:'Maximum 13 digits required',
   selecteService:'Plese selecte service type',
   salonNotFound:'Salon not found',
   successLogin:'Success login',
   notificationSettingUpdated: "Notification setting updated",
   notificationRemindersUpdated: "Notification reminders updated",
   validationFailed:"Validation failed",
   selectdate:"Please select date",
   selectTime:"please select time",
   selectServices: "Select services",
   enterPhoneNumber:"PLease Enter Phone number",
   selectCompanyAddDescription: "Please select company & add description",
   somethingWentWrong: "Something went wrong",
   checkInternet: "Please check your internet connection",
   enterPassword:'Please enter your password',
   passwordMustbeGreateDigits: 'password must be greater than 8 digits',
   validPassword: "Password must have Uppercase, Lowercase, special character and numbers",
   enterAccountName:"Please enter your Account name",
   AccountNameGreater: 'Account name should be greater than 3 characters',
   accountLessNum: 'Account name should be less than 20 digits',
   enterPhone: 'phone field must not be empty',
   phoneMax : 'Minimum 10 digits required',
   phoneMin: 'Maximum 13 digits required',
   onlyNum: 'Phone must have only numbers',
   male: 'Male',
   female: 'Female',

   // camera 
   cameraPermission:'Camera Permission',
   needsCameraPermission:'App needs camera permission',
   storageWritePermission:'External Storage Write Permission',
   cancelledCameraPicker: 'User cancelled camera picker',
   CameraNotAvailable: 'Camera not available on device',
   permissionNotSatisfied:'Permission not satisfied',
   cameraIssue :'this sis camera issue: ',
   needsWritePermission: 'App needs write permission',
   writePermissionErr:'Write permission err,',
   appriciateRatingString:"We would appriciate your rating. It will take less then a minute",
   DescribeRating:"Describe stylist rating...",
   NoBookingFound:"No Booking Found",
   availableServices:"Available services",
   resetAll : "Reset all",
   Filters:'Filters',
   PriceRange:"Price Range",
   Waiting:"Waiting",
   price:'price',
   availableTime:"Available time",
   noFOundData:"PLease select another date",
   ChooseMaster:"Choose master",
   NoDatafound:"No Data found for this service",
   Nearby:"Nearby",
   Popular:"Popular",
   Nofavoritesalonfound:"No favorite salon found",
   genderPreference:"Gender preference",
   onboardpermisionTitle:"Get ready to transform your look!"

};
export default Strings;